"""Upload DTOs (Data Transfer Objects)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from deeplecture.domain import FeatureStatus

# =============================================================================
# Request DTOs
# =============================================================================


@dataclass
class UploadVideoRequest:
    """Request to upload a single video file."""

    content_id: str  # Pre-generated by caller
    filename: str
    file_data: Any  # File-like object (framework-agnostic)


@dataclass
class UploadPDFRequest:
    """Request to upload a single PDF file."""

    content_id: str  # Pre-generated by caller
    filename: str
    file_data: Any  # File-like object (framework-agnostic)


@dataclass
class ImportVideoFromURLRequest:
    """Request to import video from URL."""

    url: str
    custom_name: str | None = None


@dataclass
class MergeVideosRequest:
    """Request to merge multiple videos."""

    file_data_list: list[Any]  # List of file-like objects
    custom_name: str
    async_mode: bool = False  # True = async via task queue


@dataclass
class MergePDFsRequest:
    """Request to merge multiple PDFs."""

    file_data_list: list[Any]  # List of file-like objects
    custom_name: str
    async_mode: bool = False  # True = async via task queue


# =============================================================================
# Response DTOs
# =============================================================================


@dataclass
class UploadResult:
    """Result of synchronous upload operation."""

    content_id: str
    filename: str
    content_type: str  # "video" or "slide"
    message: str


@dataclass
class ImportJobResult:
    """Result of async import/merge job initiation."""

    content_id: str
    filename: str
    content_type: str
    status: FeatureStatus
    message: str
    job_id: str | None = None  # Task ID if async
